import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#296678',
        'on-primary': '#ffffff',
        'primary-container': '#6ba4b8',
        'on-primary-container': '#003947',
        'primary-fixed': '#b5ebff',
        'primary-fixed-dim': '#96cfe4',
        'on-primary-fixed': '#001f28',
        'on-primary-fixed-variant': '#034e5f',
        'secondary': '#645d54',
        'on-secondary': '#ffffff',
        'secondary-container': '#e9ded2',
        'on-secondary-container': '#696258',
        'secondary-fixed': '#ece1d5',
        'secondary-fixed-dim': '#cfc5b9',
        'on-secondary-fixed': '#201b13',
        'on-secondary-fixed-variant': '#4c463d',
        'tertiary': '#84532a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ca8f61',
        'on-tertiary-container': '#512904',
        'tertiary-fixed': '#ffdcc4',
        'tertiary-fixed-dim': '#fab988',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#683c15',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fbf9f6',
        'on-background': '#1b1c1a',
        'surface': '#fbf9f6',
        'on-surface': '#1b1c1a',
        'surface-variant': '#e4e2df',
        'on-surface-variant': '#40484b',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-dim': '#dbdad7',
        'surface-bright': '#fbf9f6',
        'surface-tint': '#296678',
        'outline': '#70787c',
        'outline-variant': '#c0c8cc',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#96cfe4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'Noto Sans KR', 'sans-serif'],
        serif: ['Instrument Serif', 'serif'],
        body: ['Be Vietnam Pro', 'Noto Sans KR', 'sans-serif'],
        label: ['Be Vietnam Pro', 'Noto Sans KR', 'sans-serif'],
      },
      boxShadow: {
        'editorial': '0 12px 32px -4px rgba(28, 25, 23, 0.06)',
        'editorial-lg': '0 40px 100px -20px rgba(0, 0, 0, 0.25)',
      },
      keyframes: {
        'pulse-width': {
          '0%': { width: '10%' },
          '50%': { width: '85%' },
          '100%': { width: '95%' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(0.98)' },
        },
        'move-bg': {
          from: { transform: 'scale(1.1) translate(0, 0)' },
          to: { transform: 'scale(1.0) translate(-2%, -2%)' },
        },
      },
      animation: {
        'pulse-width': 'pulse-width 3s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        'move-bg': 'move-bg 20s infinite alternate ease-in-out',
      },
    },
  },
  plugins: [],
}
export default config
