import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#296678',
        'primary-container': '#6ba4b8',
        'primary-fixed-dim': '#96cfe4',
        'primary-fixed': '#b5ebff',
        'on-primary': '#ffffff',
        'on-primary-container': '#003947',
        'on-primary-fixed': '#001f28',
        'on-primary-fixed-variant': '#034e5f',
        surface: '#fbf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-dim': '#dbdad7',
        'surface-bright': '#fbf9f6',
        'surface-variant': '#e4e2df',
        'surface-tint': '#296678',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#40484b',
        'on-background': '#1b1c1a',
        background: '#fbf9f6',
        secondary: '#645d54',
        'secondary-container': '#e9ded2',
        'secondary-fixed': '#ece1d5',
        'secondary-fixed-dim': '#cfc5b9',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#696258',
        'on-secondary-fixed': '#201b13',
        'on-secondary-fixed-variant': '#4c463d',
        outline: '#70787c',
        'outline-variant': '#c0c8cc',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#96cfe4',
        tertiary: '#84532a',
        'tertiary-container': '#ca8f61',
        'tertiary-fixed': '#ffdcc4',
        'tertiary-fixed-dim': '#fab988',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#512904',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#683c15',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
